#!/bin/sh

action=""

case $1 in
    next)
        action="next track"
        break;;
    prev)
        action="previous track"
        break;;
esac

[ -z "$action" ] && exit 1

osascript <<EOF
tell application "iTunes"
    $action
end tell
EOF
